before:
  hooks:
    - go mod tidy
builds:
  - flags:
      - -trimpath
    env:
      - CGO_ENABLED=1
    ldflags: |
      -s -w -X "github.com/dkorunic/iSMC/cmd.GitTag={{.Tag}}" -X "github.com/dkorunic/iSMC/cmd.GitCommit={{.ShortCommit}}" -X "github.com/dkorunic/iSMC/cmd.GitDirty= " -X "github.com/dkorunic/iSMC/cmd.BuildTime={{.Date}}"
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
universal_binaries:
  - replace: true
changelog:
  sort: asc
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - src: dist/CHANGELOG.md
        dst: ""
        strip_parent: true
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
brews:
  - name: ismc
    repository:
      owner: dkorunic
      name: homebrew-tap
    homepage: https://github.com/dkorunic/iSMC
    description: Apple SMC CLI tool that can decode and display temperature, fans, battery, power, voltage and current information
    license: GPL-3.0
    test: |
      system "#{bin}/iSMC", "help"
    install: |
      bin.install "iSMC"
