#!/bin/sh
set -e

if [ -z "$1" ]; then
  echo "Missing target filename"
  exit 1
fi

T=$(awk -F: '!/^[[:space:]]*\/\// { print "    {Key:\"" $2 "\", Desc:\"" $1 "\", Platform:\"" $3 "\"}," }' < ../src/temp.txt)
F=$(awk -F: '!/^[[:space:]]*\/\// { print "    {Key:\"" $2 "\", Desc:\"" $1 "\", Platform:\"" $3 "\"}," }' < ../src/fans.txt)
P=$(awk -F: '!/^[[:space:]]*\/\// { print "    {Key:\"" $2 "\", Desc:\"" $1 "\", Platform:\"" $3 "\"}," }' < ../src/power.txt)
V=$(awk -F: '!/^[[:space:]]*\/\// { print "    {Key:\"" $2 "\", Desc:\"" $1 "\", Platform:\"" $3 "\"}," }' < ../src/voltage.txt)
C=$(awk -F: '!/^[[:space:]]*\/\// { print "    {Key:\"" $2 "\", Desc:\"" $1 "\", Platform:\"" $3 "\"}," }' < ../src/current.txt)

echo "
// Copyright (C) 2019  Dinko Korunic
// SPDX-License-Identifier: GPL-3.0-only

// Code generated by go generate. DO NOT EDIT.
// source template in smc/gen-sensors.sh

//go:build darwin

package smc

var AppleTemp = []SensorStat{
$T
}

var AppleFans = []SensorStat{
$F

}
var ApplePower = []SensorStat{
$P

}
var AppleVoltage = []SensorStat{
$V

}
var AppleCurrent = []SensorStat{
$C

}
" | gofmt > "$1"

gofumpt -w "$1" || true
