#!/bin/sh
set -e

if [ -z "$1" ]; then
  echo "Missing target filename"
  exit 1
fi

T=$(awk -F: '{ print "    {Key:\"" $2 "\", Desc:\"" $1 "\"}," }' < ../src/temp.txt)
F=$(awk -F: '{ print "    {Key:\"" $2 "\", Desc:\"" $1 "\"}," }' < ../src/fans.txt)
P=$(awk -F: '{ print "    {Key:\"" $2 "\", Desc:\"" $1 "\"}," }' < ../src/power.txt)
V=$(awk -F: '{ print "    {Key:\"" $2 "\", Desc:\"" $1 "\"}," }' < ../src/voltage.txt)
C=$(awk -F: '{ print "    {Key:\"" $2 "\", Desc:\"" $1 "\"}," }' < ../src/current.txt)

echo "
// @license
// Copyright (C) 2019  Dinko Korunic
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by go generate. DO NOT EDIT.
// source template in smc/gen-sensors.sh

// +build darwin

package smc

var AppleTemp = []SensorStat{
$T
}
var AppleFans = []SensorStat{
$F
}
var ApplePower = []SensorStat{
$P
}
var AppleVoltage = []SensorStat{
$V
}
var AppleCurrent = []SensorStat{
$C
}
" | gofmt > "$1"
