name: Lint

env:
  GO_VERSION: 1.18

permissions:
  contents: read

on:
  push:
    branches:
      - issue/gh-actions
    # paths:
    #   - "**.go"
    #   - go.mod
    #   - go.sum
  pull_request:
    # paths:
    #   - "**.go"
    #   - go.mod
    #   - go.sum

jobs:

  lint:
    name: Lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set Go Cache Paths
        id: go-cache-paths
        run: |
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - name: Restore Go Modules Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Verify modules
        run: |
          make verify

      - name: Lint code
        run: |
          make lint
